DROP TABLE IF EXISTS CUSTOMER;
 
CREATE TABLE CUSTOMER (
  id int(20) AUTO_INCREMENT  PRIMARY KEY,
  email VARCHAR(100) NOT NULL,
  first_name VARCHAR(100) NOT NULL,
  last_name VARCHAR(100) NOT NULL
);